// missions-data.js — the curated backbone of the Missions chapter: the story of
// spaceflight from Sputnik to the present, in ~60 milestones.  Every fact here
// is display copy for a family audience, held to the app's honesty bar — dates,
// crews, firsts and numbers checked against the historical record.
//
// Each mission: { id, date ('YYYY-MM-DD'), name, agency, flag, story, disc?,
//   crew?, rocket?, fly? (a deep-link spec navigateTo() understands),
//   q? (NASA image-archive search query used once by tools/fetch-mission-images.mjs) }
// The live "story continues" tail (recent + upcoming launches) is NOT here — it
// comes from public/missions/recent.json, refreshed on a schedule by CI.

export const ERAS = [
  {
    id: 'race', title: 'The race begins', span: '1957 – 1961',
    blurb: 'Two superpowers discover the sky has no ceiling. In four years: the first satellite, the first living creature in orbit, the first pictures of the far side of the Moon — and the first human being to see Earth from outside.',
  },
  {
    id: 'moon', title: 'To the Moon', span: '1962 – 1972',
    blurb: 'The most audacious engineering project in history, run twice in parallel. Twelve people walk on another world; robots land on Venus and Mars; and the whole thing is over in a decade.',
  },
  {
    id: 'grandtour', title: 'The grand tour', span: '1972 – 1989',
    blurb: 'A rare planetary alignment throws open the outer solar system, and two golden-record-carrying probes take the ride of all time. Stations replace sprints; the Shuttle promises routine — and teaches hard lessons.',
  },
  {
    id: 'neweyes', title: 'New eyes', span: '1990 – 2003',
    blurb: 'Telescopes above the atmosphere rewrite astronomy, a rover the size of a microwave charms the planet, and a permanently crewed station begins — humanity has now been off-world continuously since November 2000.',
  },
  {
    id: 'robots', title: 'The robot explorers', span: '2004 – 2014',
    blurb: 'The solar system gets a workforce: twin rovers that outlive every promise, a lander on a moon of Saturn, sample-catchers at asteroids and comets, and a nuclear-powered laboratory lowered to Mars on a rocket crane.',
  },
  {
    id: 'newspace', title: 'The new space age', span: '2015 – today',
    blurb: 'Rockets learn to land and fly again, private crews reach orbit, humanity practices deflecting an asteroid, and a gold-mirrored telescope unfolds a million miles out. The story speeds up — and it isn’t slowing down.',
  },
];

export const MISSIONS = [
  // ------------------------------------------------ the race begins ----
  { id: 'sputnik1', era: 'race', date: '1957-10-04', name: 'Sputnik 1', agency: 'USSR', flag: '🇷🇺',
    rocket: 'R-7',
    story: 'A polished 58 cm sphere with four whip antennas, beeping on a frequency any ham radio could hear — deliberately. The Space Age began as a sound the whole world could tune in to.',
    disc: 'First artificial satellite. Its decaying orbit also gave the first measurements of the upper atmosphere’s density.',
    q: 'Sputnik 1 replica' },
  { id: 'sputnik2', era: 'race', date: '1957-11-03', name: 'Sputnik 2 · Laika', agency: 'USSR', flag: '🇷🇺',
    crew: 'Laika',
    story: 'One month later, a stray dog from the Moscow streets became the first living creature to orbit Earth. There was never a plan to bring her home — a hard truth the program only admitted decades later.',
    disc: 'Proved a living being could survive launch and orbit — the door to human spaceflight.',
    q: 'Laika dog Sputnik' },
  { id: 'explorer1', era: 'race', date: '1958-01-31', name: 'Explorer 1', agency: 'USA', flag: '🇺🇸',
    rocket: 'Juno I',
    story: 'America’s answer, built in under 90 days, carried something Sputnik didn’t: a science instrument. James Van Allen’s Geiger counter kept saturating — because Earth, it turned out, is wrapped in belts of trapped radiation.',
    disc: 'The Van Allen radiation belts — the first discovery of the Space Age.',
    q: 'Explorer 1' },
  { id: 'luna2', era: 'race', date: '1959-09-13', name: 'Luna 2', agency: 'USSR', flag: '🇷🇺',
    story: 'The first human-made object to touch another world — by hitting it at 3 km/s. It scattered Soviet pennants across the lunar plains and proved the Moon has no significant magnetic field.',
    disc: 'First spacecraft to reach the Moon.',
    q: 'Luna 2 soviet' },
  { id: 'luna3', era: 'race', date: '1959-10-04', name: 'Luna 3', agency: 'USSR', flag: '🇷🇺',
    story: 'For all of human history, half the Moon had never been seen. Luna 3 looped behind it, photographed the far side on film, developed the film on board, and faxed the grainy frames home.',
    disc: 'The far side is strikingly different — almost no dark maria. A puzzle still being worked on today.',
    fly: { luna: true },
    q: 'Luna 3 far side' },
  { id: 'tiros1', era: 'race', date: '1960-04-01', name: 'TIROS-1', agency: 'NASA', flag: '🇺🇸',
    story: 'The first weather satellite sent back 19,000 fuzzy television pictures of clouds — and forecasting changed forever. Every hurricane you have ever watched from above descends from this little drum.',
    disc: 'Proved weather could be watched from orbit.',
    q: 'TIROS-1 weather satellite' },
  { id: 'vostok1', era: 'race', date: '1961-04-12', name: 'Vostok 1 · Yuri Gagarin', agency: 'USSR', flag: '🇷🇺',
    crew: 'Yuri Gagarin', rocket: 'Vostok-K',
    story: '“Poyekhali!” — let’s go. One 108-minute orbit, one 27-year-old test pilot, and humanity became a spacefaring species. He ejected as designed and parachuted into a field, startling a farmer and her granddaughter.',
    disc: 'First human in space, first human in orbit.',
    q: 'Yuri Gagarin' },
  { id: 'freedom7', era: 'race', date: '1961-05-05', name: 'Freedom 7 · Alan Shepard', agency: 'NASA', flag: '🇺🇸',
    crew: 'Alan Shepard', rocket: 'Mercury-Redstone',
    story: 'Fifteen minutes of flight, watched live by 45 million people. Three weeks later, Kennedy stood before Congress and aimed the country at the Moon — before America had even put a person in orbit.',
    disc: 'First American in space; the flight that set up the Moon decision.',
    q: 'Alan Shepard Freedom 7' },

  // ------------------------------------------------ to the Moon ----
  { id: 'friendship7', era: 'moon', date: '1962-02-20', name: 'Friendship 7 · John Glenn', agency: 'NASA', flag: '🇺🇸',
    crew: 'John Glenn', rocket: 'Mercury-Atlas',
    story: 'Three orbits with a suspect heat-shield warning light and a pilot calm enough to describe “fireflies” outside his window. Glenn returned to the biggest American hero’s welcome since Lindbergh — and flew again at 77.',
    disc: 'First American to orbit Earth.',
    q: 'John Glenn Friendship 7' },
  { id: 'mariner2', era: 'moon', date: '1962-12-14', name: 'Mariner 2 at Venus', agency: 'NASA', flag: '🇺🇸',
    story: 'The first successful mission to another planet swept past Venus and destroyed a fantasy: no swamps, no oceans — a surface hot enough to melt lead under crushing clouds.',
    disc: 'Venus is a furnace (~430 °C): the first hard data on a runaway greenhouse.',
    fly: { body: 'Venus' },
    q: 'Mariner 2' },
  { id: 'vostok6', era: 'moon', date: '1963-06-16', name: 'Vostok 6 · Valentina Tereshkova', agency: 'USSR', flag: '🇷🇺',
    crew: 'Valentina Tereshkova',
    story: 'A textile worker and amateur parachutist became the first woman in space, flying 48 orbits — more time in orbit than every American astronaut to that date combined.',
    disc: 'First woman in space. It would be 19 more years before the second.',
    q: 'Valentina Tereshkova' },
  { id: 'voskhod2', era: 'moon', date: '1965-03-18', name: 'Voskhod 2 · the first spacewalk', agency: 'USSR', flag: '🇷🇺',
    crew: 'Alexei Leonov, Pavel Belyayev',
    story: 'Leonov floated free for 12 minutes — then his suit ballooned so stiff he couldn’t fit back through the airlock, and he bled air out of it to squeeze home. The crew then landed off-course and spent a night among wolves.',
    disc: 'First spacewalk (EVA) in history.',
    q: 'Alexei Leonov spacewalk' },
  { id: 'mariner4', era: 'moon', date: '1965-07-15', name: 'Mariner 4 at Mars', agency: 'NASA', flag: '🇺🇸',
    story: 'The first close-up pictures of another planet — 21 frames, painstakingly radioed home at 8⅓ bits per second while engineers hand-colored a printout by number because they couldn’t wait.',
    disc: 'A cratered, apparently dead Mars — ending the canal era and resetting the search for life.',
    fly: { body: 'Mars' },
    q: 'Mariner 4 Mars' },
  { id: 'gemini', era: 'moon', date: '1965-03-23', name: 'Project Gemini', agency: 'NASA', flag: '🇺🇸',
    crew: '16 astronauts, 10 crewed flights',
    story: 'The unglamorous middle child that made Apollo possible: rendezvous, docking, spacewalks that actually worked, and two weeks in a cabin the size of a car’s front seat.',
    disc: 'Every technique a Moon landing needs, proven in Earth orbit.',
    q: 'Gemini spacewalk Ed White' },
  { id: 'luna9', era: 'moon', date: '1966-02-03', name: 'Luna 9', agency: 'USSR', flag: '🇷🇺',
    story: 'An airbag-cushioned pod bounced onto the Ocean of Storms, opened like a flower, and sent the first photographs from the surface of another world — settling a real fear that landers would sink into deep dust.',
    disc: 'First soft landing on the Moon; the surface holds your weight.',
    fly: { luna: true },
    q: 'Luna 9' },
  { id: 'apollo1', era: 'moon', date: '1967-01-27', name: 'Apollo 1', agency: 'NASA', flag: '🇺🇸',
    crew: 'Gus Grissom, Ed White, Roger Chaffee',
    story: 'A fire during a routine pad test killed the crew in seconds, in a pure-oxygen cabin with a hatch that opened inward. The program stopped, rebuilt the spacecraft, and carried their names to the Moon.',
    disc: 'The hardest lesson: spaceflight is unforgiving of shortcuts. Apollo was safer for it.',
    q: 'Apollo 1 crew' },
  { id: 'apollo8', era: 'moon', date: '1968-12-21', name: 'Apollo 8', agency: 'NASA', flag: '🇺🇸',
    crew: 'Frank Borman, Jim Lovell, Bill Anders', rocket: 'Saturn V',
    story: 'The first humans to leave Earth’s gravity, on the first crewed Saturn V, reading Genesis to a billion people from lunar orbit on Christmas Eve. Anders’ off-script photo of the rising Earth became an icon of the environmental movement.',
    disc: '“Earthrise” — we went to the Moon and discovered the Earth.',
    fly: { luna: true },
    q: 'Earthrise Apollo 8' },
  { id: 'apollo11', era: 'moon', date: '1969-07-20', name: 'Apollo 11', agency: 'NASA', flag: '🇺🇸',
    crew: 'Neil Armstrong, Buzz Aldrin, Michael Collins', rocket: 'Saturn V',
    story: 'Armstrong flew the final approach by hand, past a boulder field, landing with roughly 20 seconds of fuel margin while 600 million people held their breath. The footprints at Tranquility Base will outlast every building on Earth.',
    disc: '“One small step” — 21.5 kg of Moon rock and proof the impossible schedule was met.',
    fly: { luna: true },
    q: 'Apollo 11 Aldrin' },
  { id: 'apollo13', era: 'moon', date: '1970-04-11', name: 'Apollo 13', agency: 'NASA', flag: '🇺🇸',
    crew: 'Jim Lovell, Jack Swigert, Fred Haise',
    story: 'An oxygen tank exploded 330,000 km from home. Three men in a freezing lunar module built a CO₂ scrubber out of duct tape and flight-plan covers, slingshotted around the Moon, and made it back.',
    disc: 'NASA’s finest hour that never touched the Moon — the case study in engineering under pressure.',
    q: 'Apollo 13 mission control' },
  { id: 'venera7', era: 'moon', date: '1970-12-15', name: 'Venera 7', agency: 'USSR', flag: '🇷🇺',
    story: 'After a decade of Venus probes crushed, cooked, or lost, Venera 7 hit the surface hard, rolled onto its side — and kept whispering for 23 minutes. The first data ever sent from the surface of another planet.',
    disc: 'Surface conditions on Venus: ~465 °C and 90 atmospheres.',
    fly: { body: 'Venus' },
    q: 'Venera spacecraft' },
  { id: 'luna16', era: 'moon', date: '1970-09-24', name: 'Luna 16 & Lunokhod 1', agency: 'USSR', flag: '🇷🇺',
    story: 'The robotic counterpoint to Apollo: Luna 16 drilled, sealed, and flew 101 grams of Moon home with no one aboard, and two months later Lunokhod 1 — an eight-wheeled bathtub on wheels — became the first rover on another world.',
    disc: 'Sample return and roving, both done robotically in 1970.',
    fly: { luna: true },
    q: 'Lunokhod 1' },
  { id: 'apollo17', era: 'moon', date: '1972-12-11', name: 'Apollo 17', agency: 'NASA', flag: '🇺🇸',
    crew: 'Gene Cernan, Harrison Schmitt, Ron Evans',
    story: 'The only geologist to walk the Moon found orange volcanic glass; the crew drove 36 km and brought home 110 kg of rock. Cernan’s last steps — December 1972 — are still the most recent human footprints on another world.',
    disc: 'The scientific peak of Apollo, and its ending.',
    fly: { luna: true },
    q: 'Apollo 17 Cernan' },

  // ------------------------------------------------ the grand tour ----
  { id: 'salyut1', era: 'grandtour', date: '1971-04-19', name: 'Salyut 1', agency: 'USSR', flag: '🇷🇺',
    story: 'The first space station. Its first full crew lived aboard 23 days — then died on re-entry when a valve vented their cabin to vacuum. Cosmonauts have worn pressure suits for launch and landing ever since.',
    disc: 'Living in space works; coming home is where the margins are thinnest.',
    q: 'Salyut 1 station' },
  { id: 'mariner9', era: 'grandtour', date: '1971-11-14', name: 'Mariner 9', agency: 'NASA', flag: '🇺🇸',
    story: 'The first spacecraft to orbit another planet arrived to find Mars erased by a global dust storm — so it waited. The dust settled to reveal a canyon that would stretch across America and volcanoes three times Everest’s height.',
    disc: 'Valles Marineris and Olympus Mons: Mars is a world with a dramatic past.',
    fly: { probe: 'Mariner 9' },
    q: 'Mariner 9 Mars' },
  { id: 'pioneer10', era: 'grandtour', date: '1972-03-03', name: 'Pioneer 10', agency: 'NASA', flag: '🇺🇸',
    story: 'The first craft to cross the asteroid belt — then thought a possibly lethal barrier — and the first to fly past Jupiter, carrying a gold plaque showing two humans and our address among the stars.',
    disc: 'The road to the outer planets is open.',
    fly: { show: 'pioneer10' },
    q: 'Pioneer 10 plaque' },
  { id: 'skylab', era: 'grandtour', date: '1973-05-14', name: 'Skylab', agency: 'NASA', flag: '🇺🇸',
    story: 'America’s first station launched damaged — and its first crew fixed it with a parasol sunshade deployed through an airlock, the save that proved humans in space earn their keep. Three crews logged 171 days aboard.',
    disc: 'Long-duration spaceflight medicine and the first solar observatory staffed by people.',
    q: 'Skylab station' },
  { id: 'mariner10', era: 'grandtour', date: '1973-11-03', name: 'Mariner 10', agency: 'NASA', flag: '🇺🇸',
    story: 'The first mission to use one planet’s gravity to reach another — a Venus flyby bent it into Mercury’s neighborhood three times over. The gravity assist became the master key to the solar system.',
    disc: 'Mercury: cratered, iron-hearted, and 45% mapped in one mission.',
    fly: { body: 'Mercury' },
    q: 'Mariner 10 Mercury' },
  { id: 'venera9', era: 'grandtour', date: '1975-10-22', name: 'Venera 9', agency: 'USSR', flag: '🇷🇺',
    story: 'Fifty-three minutes of transmissions from a pressure-cooker world, including the picture no one had ever seen: the surface of another planet, sharp volcanic rocks under a sky the color of dishwater.',
    disc: 'The first photograph from another planet’s surface.',
    fly: { body: 'Venus' },
    q: 'Venera 9 surface' },
  { id: 'astp', era: 'grandtour', date: '1975-07-15', name: 'Apollo–Soyuz', agency: 'NASA + USSR', flag: '🤝',
    crew: 'Stafford, Brand, Slayton · Leonov, Kubasov',
    story: 'The Cold War rivals docked 220 km up and shook hands through the hatch — Leonov, the first spacewalker, greeting Stafford in deliberately terrible Oklahoma-accented Russian. Détente, with orbital mechanics.',
    disc: 'The handshake that previewed Mir-Shuttle and the ISS.',
    q: 'Apollo Soyuz handshake' },
  { id: 'viking', era: 'grandtour', date: '1976-07-20', name: 'Viking 1 & 2', agency: 'NASA', flag: '🇺🇸',
    story: 'Seven years to the day after Apollo 11, Viking 1 sent the first photograph from the surface of Mars. Two orbiters mapped the planet; two landers ran the first life-detection experiments on another world — with results argued about to this day.',
    disc: 'Mars up close: frost, pink skies, and chemistry strange enough to keep the life question open.',
    fly: { probe: 'Viking 1 Orbiter' },
    q: 'Viking lander Mars surface' },
  { id: 'voyager', era: 'grandtour', date: '1977-08-20', name: 'Voyager 1 & 2', agency: 'NASA', flag: '🇺🇸',
    rocket: 'Titan IIIE',
    story: 'A once-in-176-years planetary alignment let two probes tour all four giant planets on gravity alone. They found volcanoes on Io, a possible ocean under Europa, geysers on Triton — and each carries a golden record of Earth’s music, greetings, and a heartbeat.',
    disc: 'The definitive first reconnaissance of the outer solar system, still calling home from interstellar space.',
    fly: { show: 'voyager1' },
    q: 'Voyager golden record' },
  { id: 'gps1', era: 'grandtour', date: '1978-02-22', name: 'Navstar 1 · GPS begins', agency: 'US Air Force', flag: '🇺🇸',
    story: 'The first satellite of a system designed to guide submarines and bombers now guides everyone, everywhere, for free. Every blue dot on every phone map descends from this launch.',
    disc: 'Satellite navigation — arguably the most-used thing ever put in space.',
    fly: { group: 'gps' },
    q: 'GPS Navstar satellite' },
  { id: 'sts1', era: 'grandtour', date: '1981-04-12', name: 'STS-1 · Columbia', agency: 'NASA', flag: '🇺🇸',
    crew: 'John Young, Bob Crippen', rocket: 'Space Shuttle',
    story: 'Twenty years to the day after Gagarin, the first reusable spaceship flew its first mission — with a crew aboard, a test-flight gamble never repeated. It came home missing tiles, and landed like an airliner.',
    disc: 'The winged, reusable era begins: 135 flights over 30 years.',
    q: 'STS-1 Columbia launch' },
  { id: 'venera13', era: 'grandtour', date: '1982-03-01', name: 'Venera 13', agency: 'USSR', flag: '🇷🇺',
    story: 'Built to survive half an hour, it lasted 127 minutes in lead-melting heat — long enough to send the first color panoramas of Venus and drill the surface. Some of the hardest engineering ever done, for two hours of glory.',
    disc: 'Venus in color: an orange rock-strewn plain under a sulfurous sky.',
    fly: { body: 'Venus' },
    q: 'Venera 13 color surface' },
  { id: 'sallyride', era: 'grandtour', date: '1983-06-18', name: 'STS-7 · Sally Ride', agency: 'NASA', flag: '🇺🇸',
    crew: 'Sally Ride + 4',
    story: 'The first American woman in space fielded press questions about makeup and bathrooms with a physicist’s patience, flew the robot arm flawlessly, and changed who kids pictured when they heard “astronaut.”',
    disc: 'The astronaut corps starts to look like the country it flies for.',
    q: 'Sally Ride' },
  { id: 'challenger', era: 'grandtour', date: '1986-01-28', name: 'Challenger · STS-51L', agency: 'NASA', flag: '🇺🇸',
    crew: 'Scobee, Smith, Resnik, Onizuka, McNair, Jarvis, McAuliffe',
    story: 'Seventy-three seconds after launch, on a morning too cold for its booster seals, Challenger broke apart with a teacher aboard and schoolchildren watching. The inquiry exposed how schedule pressure had quietly beaten engineering judgment.',
    disc: 'Normalization of deviance entered the language; flight safety was rebuilt around it.',
    q: 'Challenger crew STS-51L' },
  { id: 'mir', era: 'grandtour', date: '1986-02-19', name: 'Mir', agency: 'USSR / Russia', flag: '🇷🇺',
    story: 'The first modular station, assembled in orbit over a decade, home to the longest single spaceflight ever — Valeri Polyakov’s 437 days. It survived a fire, a collision, and the collapse of the country that launched it.',
    disc: 'Permanent presence in space is possible — and the ISS’s blueprint.',
    q: 'Mir space station' },
  { id: 'giotto', era: 'grandtour', date: '1986-03-13', name: 'Giotto at Halley', agency: 'ESA', flag: '🇪🇺',
    story: 'Europe’s first deep-space mission flew into the coma of Halley’s Comet at 68 km/s, was blinded by a dust strike seconds before closest approach — and still returned the first images of a comet’s nucleus: a black peanut spitting jets of gas.',
    disc: 'Comet nuclei are darker than coal — primordial leftovers, not dirty snowballs of ice alone.',
    fly: { body: 'Halley' },
    q: 'Giotto Halley nucleus' },
  { id: 'magellan', era: 'grandtour', date: '1989-05-04', name: 'Magellan', agency: 'NASA', flag: '🇺🇸',
    story: 'Radar sees through anything, even Venus’s permanent overcast. Magellan mapped 98% of the planet, revealing a young volcanic surface with almost no ancient craters — a world that resurfaces itself.',
    disc: 'Venus’s global portrait, still the best map of the planet we have.',
    fly: { probe: 'Magellan' },
    q: 'Magellan Venus radar' },

  // ------------------------------------------------ new eyes ----
  { id: 'hubble', era: 'neweyes', date: '1990-04-24', name: 'Hubble Space Telescope', agency: 'NASA / ESA', flag: '🇺🇸',
    story: 'Launched with a famously flawed mirror, rescued by spacewalking opticians in 1993, and then it simply rewrote astronomy: the universe’s age pinned down, black holes weighed, deep fields where “empty” sky became ten thousand galaxies.',
    disc: 'Thirty-five years of discovery — and it’s still working overhead. You can fly to the real one.',
    fly: { sat: '20580' },
    q: 'Hubble Space Telescope deployment' },
  { id: 'galileo', era: 'neweyes', date: '1995-12-07', name: 'Galileo at Jupiter', agency: 'NASA', flag: '🇺🇸',
    story: 'It dropped a probe into Jupiter’s clouds, watched a comet chain slam into the planet, and found the evidence that Europa hides a saltwater ocean — then was deliberately flown into Jupiter to protect that ocean from Earth microbes.',
    disc: 'Europa’s ocean: the solar system’s most tantalizing address for life.',
    fly: { probe: 'Galileo' },
    q: 'Galileo spacecraft Jupiter' },
  { id: 'soho', era: 'neweyes', date: '1995-12-02', name: 'SOHO', agency: 'ESA / NASA', flag: '🇪🇺',
    story: 'Parked where Earth’s and the Sun’s gravity balance, SOHO has watched the Sun without blinking for three decades — and become history’s greatest comet-finder by accident, with over 5,000 spotted grazing the Sun.',
    disc: 'Space weather forecasting begins here; your power grid quietly depends on it.',
    fly: { show: 'soho' },
    q: 'SOHO spacecraft sun' },
  { id: 'pathfinder', era: 'neweyes', date: '1997-07-04', name: 'Mars Pathfinder & Sojourner', agency: 'NASA', flag: '🇺🇸',
    story: 'Landed on airbags, cost a tenth of Viking, and its microwave-oven-sized rover became a 90s celebrity — the mission’s website drew what were then the largest crowds in internet history.',
    disc: 'Cheap, bold missions work — and rovers are how you do Mars.',
    fly: { body: 'Mars' },
    q: 'Sojourner rover Pathfinder' },
  { id: 'cassini', era: 'neweyes', date: '1997-10-15', name: 'Cassini–Huygens', agency: 'NASA / ESA / ASI', flag: '🤝',
    story: 'Thirteen years at Saturn: it landed Europe’s Huygens probe on Titan — the most distant landing ever — flew through the ice geysers of Enceladus, and ended in 2017 by diving into Saturn itself, sending data to the last second.',
    disc: 'Two new worlds for the life question: Titan’s methane seas and Enceladus’s salty plumes.',
    fly: { probe: 'Cassini' },
    q: 'Cassini Saturn' },
  { id: 'iss', era: 'neweyes', date: '1998-11-20', name: 'International Space Station', agency: '15 nations', flag: '🤝',
    story: 'Begun with a Russian module and assembled over 40+ flights into the largest structure ever flown, it has been continuously inhabited since November 2000 — an entire generation has never known a day with no one in space. It’s overhead right now.',
    disc: 'The longest-running laboratory off Earth — and proof rivals can build together.',
    fly: { sat: '25544' },
    q: 'International Space Station' },
  { id: 'chandra', era: 'neweyes', date: '1999-07-23', name: 'Chandra X-ray Observatory', agency: 'NASA', flag: '🇺🇸',
    story: 'The universe’s violent side — matter shrieking into black holes, exploded stars, galaxy clusters — glows in X-rays that never reach the ground. Chandra has imaged it for a quarter century, deployed by Eileen Collins, the first female shuttle commander.',
    disc: 'Black holes went from theory to census.',
    fly: { sat: '25867' },
    q: 'Chandra X-ray Observatory' },
  { id: 'near', era: 'neweyes', date: '2001-02-12', name: 'NEAR Shoemaker lands on Eros', agency: 'NASA', flag: '🇺🇸',
    story: 'After a year orbiting the asteroid Eros, engineers tried something the spacecraft was never designed for: landing. It touched down at walking pace and kept transmitting from the surface for two weeks.',
    disc: 'First landing on an asteroid — improvised, and it worked.',
    q: 'NEAR Shoemaker Eros' },
  { id: 'columbia', era: 'neweyes', date: '2003-02-01', name: 'Columbia · STS-107', agency: 'NASA', flag: '🇺🇸',
    crew: 'Husband, McCool, Anderson, Chawla, Brown, Clark, Ramon',
    story: 'A briefcase-sized piece of foam, shed at launch and dismissed as routine, had holed the wing. Columbia broke apart during re-entry after sixteen days of science. The loss reshaped the program and set the Shuttle’s retirement date.',
    disc: 'The second hard lesson in “proven” systems — and the pivot toward what came next.',
    q: 'Columbia STS-107 crew' },
  { id: 'marsexpress', era: 'neweyes', date: '2003-06-02', name: 'Mars Express', agency: 'ESA', flag: '🇪🇺',
    story: 'Europe’s first planetary orbiter is still working after two decades: its radar found buried water ice across Mars and evidence of a possible salty lake beneath the south polar cap.',
    disc: 'Mars has water — frozen, buried, and possibly liquid at depth.',
    fly: { probe: 'Mars Express' },
    q: 'Mars Express ESA' },

  // ------------------------------------------------ the robot explorers ----
  { id: 'mer', era: 'robots', date: '2004-01-04', name: 'Spirit & Opportunity', agency: 'NASA', flag: '🇺🇸',
    story: 'Twin rovers with 90-day warranties. Spirit drove six years; Opportunity drove almost fifteen and a marathon’s distance, dying in a dust storm after 5,111 sols. Its final data was, in effect: my battery is low and it’s getting dark.',
    disc: 'Standing water once pooled on Mars — the rovers found the shorelines’ chemistry.',
    fly: { body: 'Mars' },
    q: 'Opportunity rover Mars' },
  { id: 'huygens', era: 'robots', date: '2005-01-14', name: 'Huygens lands on Titan', agency: 'ESA', flag: '🇪🇺',
    story: 'A parachute descent through orange haze onto a frozen riverbed a billion kilometres away — the most distant landing ever attempted. It photographed drainage channels carved not by water, but by liquid methane rain.',
    disc: 'Titan is a hauntingly Earth-like world running on entirely different chemistry.',
    fly: { moon: 'Titan' },
    q: 'Huygens Titan surface' },
  { id: 'deepimpact', era: 'robots', date: '2005-07-04', name: 'Deep Impact', agency: 'NASA', flag: '🇺🇸',
    story: 'On the Fourth of July, NASA shot a copper block into comet Tempel 1 at 37,000 km/h just to see what would fly out. The answer: a surprising powder of ice and organic dust — a comet is fluffier than fresh snow.',
    disc: 'A comet’s insides, excavated on live television.',
    q: 'Deep Impact comet Tempel' },
  { id: 'mro', era: 'robots', date: '2006-03-10', name: 'Mars Reconnaissance Orbiter', agency: 'NASA', flag: '🇺🇸',
    story: 'Carrying the sharpest camera ever sent to another planet, MRO has photographed avalanches mid-fall, new impact craters exposing buried ice, and every rover from orbit — while relaying most of their data home.',
    disc: 'Twenty years of watching Mars change in real time.',
    fly: { probe: 'MRO' },
    q: 'Mars Reconnaissance Orbiter HiRISE' },
  { id: 'kepler', era: 'robots', date: '2009-03-07', name: 'Kepler', agency: 'NASA', flag: '🇺🇸',
    story: 'It stared at one patch of sky for nine years, watching 150,000 stars for the faintest blink of a passing planet. Verdict: planets outnumber stars in our galaxy, and small rocky worlds are common.',
    disc: 'Thousands of exoplanets — and the statistical certainty of billions more.',
    fly: { show: 'kepler' },
    q: 'Kepler space telescope' },
  { id: 'hayabusa', era: 'robots', date: '2010-06-13', name: 'Hayabusa returns', agency: 'JAXA', flag: '🇯🇵',
    story: 'Japan’s little probe survived engine failures, fuel leaks, and lost contact to become the first mission to bring home a piece of an asteroid — a capsule streaking into the Australian outback with grains of Itokawa aboard.',
    disc: 'First asteroid sample return, against all odds.',
    q: 'Hayabusa capsule return' },
  { id: 'messenger', era: 'robots', date: '2011-03-18', name: 'MESSENGER orbits Mercury', agency: 'NASA', flag: '🇺🇸',
    story: 'It took six planetary flybys just to slow down enough to stay. The first Mercury orbiter mapped the whole planet — and found water ice hiding in polar craters on the closest world to the Sun.',
    disc: 'Ice on Mercury: permanently shadowed craters are cold traps even in a furnace.',
    fly: { probe: 'MESSENGER' },
    q: 'MESSENGER Mercury' },
  { id: 'curiosity', era: 'robots', date: '2012-08-06', name: 'Curiosity · seven minutes of terror', agency: 'NASA', flag: '🇺🇸',
    story: 'A one-ton nuclear-powered laboratory, lowered onto Mars by a hovering rocket crane that then flew away and crashed itself on purpose — a landing so absurd its own engineers called it crazy. It worked perfectly, and the rover is still climbing.',
    disc: 'Gale Crater was a habitable lake, with every ingredient life needs.',
    fly: { body: 'Mars' },
    q: 'Curiosity rover self portrait' },
  { id: 'v1interstellar', era: 'robots', date: '2012-08-25', name: 'Voyager 1 goes interstellar', agency: 'NASA', flag: '🇺🇸',
    story: 'Thirty-five years after launch, Voyager 1 crossed the boundary where the Sun’s wind gives way to the gas between the stars — the first human-made object in interstellar space, its 1970s transmitter still whispering home.',
    disc: 'We are, in a small way, an interstellar species now.',
    fly: { show: 'voyager1' },
    q: 'Voyager 1 interstellar' },
  { id: 'change3', era: 'robots', date: '2013-12-14', name: 'Chang’e 3 & Yutu', agency: 'CNSA', flag: '🇨🇳',
    story: 'The first soft landing on the Moon in 37 years — and China’s first — with the Yutu (“Jade Rabbit”) rover rolling onto Mare Imbrium. A statement of arrival from a new major spacefaring power.',
    disc: 'The Moon has a new visitor, and lunar exploration a new era.',
    fly: { luna: true },
    q: 'Change 3 Yutu rover' },
  { id: 'rosetta', era: 'robots', date: '2014-11-12', name: 'Rosetta & Philae', agency: 'ESA', flag: '🇪🇺',
    story: 'After a ten-year chase, Rosetta orbited a comet and dropped Philae — which bounced a kilometre high in the feeble gravity, landed in a shadowed crack, and still did science on battery power while the world rooted for it.',
    disc: 'Comets carry organic molecules — and water unlike Earth’s oceans, deepening the mystery of where ours came from.',
    q: 'Rosetta Philae comet 67P' },
  { id: 'mom', era: 'robots', date: '2014-09-24', name: 'Mangalyaan (MOM)', agency: 'ISRO', flag: '🇮🇳',
    story: 'India reached Mars orbit on its very first interplanetary attempt — something no other nation had done — for a budget famously smaller than the movie “Gravity.”',
    disc: 'Interplanetary flight is no longer a superpowers-only club.',
    fly: { probe: 'Mangalyaan' },
    q: 'Mars Orbiter Mission ISRO' },

  // ------------------------------------------------ the new space age ----
  { id: 'dawnceres', era: 'newspace', date: '2015-03-06', name: 'Dawn at Ceres', agency: 'NASA', flag: '🇺🇸',
    story: 'Ion engines — thrust you could hold in your hand, sustained for years — let one spacecraft orbit two different worlds: the protoplanet Vesta, then Ceres, where mysterious white spots turned out to be salt from a briny interior.',
    disc: 'Ceres is a water-rich world; the asteroid belt has an ocean story of its own.',
    fly: { body: 'Ceres' },
    q: 'Dawn Ceres bright spots' },
  { id: 'newhorizons', era: 'newspace', date: '2015-07-14', name: 'New Horizons at Pluto', agency: 'NASA', flag: '🇺🇸',
    story: 'Nine and a half years and five billion kilometres for one screaming flyby — and Pluto turned out to have a heart: a nitrogen-ice glacier the size of Texas, mountains of water ice, and blue skies. Aboard rides some of discoverer Clyde Tombaugh’s ashes.',
    disc: 'Pluto is alive geologically — small worlds aren’t boring after all.',
    fly: { body: 'Pluto' },
    q: 'New Horizons Pluto heart' },
  { id: 'f9landing', era: 'newspace', date: '2015-12-21', name: 'Falcon 9 lands', agency: 'SpaceX', flag: '🇺🇸',
    story: 'After delivering its payload to orbit, the first stage turned around, flew home, and landed standing up — the trick that had eluded rocketry for sixty years. Boosters now land routinely and fly twenty-plus times each.',
    disc: 'Reusability cracked the economics of spaceflight — the reason launches now happen twice a week.',
    q: 'Falcon 9 first landing' },
  { id: 'juno', era: 'newspace', date: '2016-07-04', name: 'Juno at Jupiter', agency: 'NASA', flag: '🇺🇸',
    story: 'Slung into a daring polar orbit that dives between Jupiter and its radiation belts, Juno photographed the poles no one had ever seen — vast geometric storm clusters — and peered through the clouds to the planet’s dissolved core.',
    disc: 'Jupiter inside and out: its storms run deep, its core is fuzzy, its poles are art.',
    fly: { probe: 'Juno' },
    q: 'Juno Jupiter poles' },
  { id: 'parker', era: 'newspace', date: '2018-08-12', name: 'Parker Solar Probe', agency: 'NASA', flag: '🇺🇸',
    story: 'The fastest thing humanity has ever built — 690,000 km/h at closest approach — repeatedly flies through the Sun’s corona behind a carbon shield. On Christmas Eve 2024 it passed just 6.1 million km from the surface. It carries the name of a living scientist who got to watch.',
    disc: 'We have touched the Sun and sampled its atmosphere in place.',
    fly: { show: 'parker' },
    q: 'Parker Solar Probe' },
  { id: 'change4', era: 'newspace', date: '2019-01-03', name: 'Chang’e 4 on the far side', agency: 'CNSA', flag: '🇨🇳',
    story: 'The far side of the Moon never faces Earth, so no lander had ever gone — there’s no direct radio path. China solved it with a relay satellite parked beyond the Moon, then landed where no one ever had.',
    disc: 'First landing on the lunar far side.',
    fly: { luna: true },
    q: 'Change 4 far side moon' },
  { id: 'starlink', era: 'newspace', date: '2019-05-24', name: 'Starlink begins', agency: 'SpaceX', flag: '🇺🇸',
    story: 'Sixty flat-packed satellites in one launch, then sixty more, then thousands: within five years one constellation held more than half of all active satellites, beaming internet to places wires never reached — and permanently changing the night sky.',
    disc: 'The megaconstellation era — you can watch the whole shell in this app.',
    fly: { group: 'starlink' },
    q: 'Starlink satellites stack' },
  { id: 'demo2', era: 'newspace', date: '2020-05-30', name: 'Crew Dragon Demo-2', agency: 'SpaceX / NASA', flag: '🇺🇸',
    crew: 'Bob Behnken, Doug Hurley',
    story: 'Nine years after the last Shuttle, astronauts launched from American soil again — this time in a capsule built and operated by a private company, with touchscreens where a thousand switches used to be.',
    disc: 'Commercial human spaceflight became real.',
    fly: { sat: '25544' },
    q: 'Crew Dragon Demo-2 launch' },
  { id: 'samples2020', era: 'newspace', date: '2020-12-06', name: 'Hayabusa2 & Chang’e 5', agency: 'JAXA · CNSA', flag: '🤝',
    story: 'In the same month, Japan dropped off pristine grains of asteroid Ryugu — rich in organics and water-bearing minerals — and China flew home the first Moon rocks since 1976, from a volcanic plain younger than any Apollo site.',
    disc: 'Sample return became routine: the solar system now ships to Earth labs.',
    q: 'Hayabusa2 Ryugu sample' },
  { id: 'perseverance', era: 'newspace', date: '2021-02-18', name: 'Perseverance & Ingenuity', agency: 'NASA', flag: '🇺🇸',
    story: 'A rover that caches samples for a future pickup — and a 1.8 kg helicopter that made the first powered flight on another planet, a Wright-brothers moment carrying a stamp-sized piece of the actual Wright Flyer’s wing. Built for 5 flights, it made 72.',
    disc: 'Flight works on Mars, and the first samples for return to Earth are sealed and waiting.',
    fly: { body: 'Mars' },
    q: 'Ingenuity helicopter Mars' },
  { id: 'tiangong', era: 'newspace', date: '2021-04-29', name: 'Tiangong', agency: 'CNSA', flag: '🇨🇳',
    story: 'China assembled its own three-module station in under two years and has kept it permanently crewed since — the second continuously inhabited outpost off Earth, and it’s trackable right here.',
    disc: 'Two crews are now off-planet at any given moment.',
    fly: { sat: '48274' },
    q: 'Tiangong space station' },
  { id: 'jwst', era: 'newspace', date: '2021-12-25', name: 'James Webb Space Telescope', agency: 'NASA / ESA / CSA', flag: '🤝',
    story: 'A gold-plated, tennis-court-sized origami telescope that had to execute 344 single-point-of-failure deployments a million miles from any repair crew. Every one worked. It now reads the atmospheres of other worlds and photographs the first galaxies.',
    disc: 'The infant universe, in focus — galaxies earlier and stranger than theory expected.',
    fly: { show: 'jwst' },
    q: 'James Webb Space Telescope mirror' },
  { id: 'dart', era: 'newspace', date: '2022-09-26', name: 'DART', agency: 'NASA', flag: '🇺🇸',
    story: 'Humanity’s first planetary-defense test: slam a vending-machine-sized spacecraft into asteroid Dimorphos at 22,000 km/h and see if its orbit budges. It budged — by 32 minutes, far more than predicted.',
    disc: 'We can move an asteroid. The dinosaurs would have appreciated this.',
    q: 'DART Dimorphos impact' },
  { id: 'artemis1', era: 'newspace', date: '2022-11-16', name: 'Artemis I', agency: 'NASA', flag: '🇺🇸',
    story: 'The most powerful rocket ever flown to that date sent an uncrewed Orion capsule around the Moon and back — the shakedown cruise for the program that intends to return people, including the first woman, to the lunar surface.',
    disc: 'The road back to the Moon is open again, fifty years after Apollo 17.',
    fly: { luna: true },
    q: 'Artemis 1 launch SLS' },
  { id: 'chandrayaan3', era: 'newspace', date: '2023-08-23', name: 'Chandrayaan-3', agency: 'ISRO', flag: '🇮🇳',
    story: 'Four years after a heartbreaking crash on its first try, India landed softly near the Moon’s south polar region — first nation to do so — while the country watched in classrooms and cricket stadiums.',
    disc: 'The Moon’s water-hunting south polar frontier has its first successful lander.',
    fly: { luna: true },
    q: 'Chandrayaan-3 landing' },
  { id: 'osirisrex', era: 'newspace', date: '2023-09-24', name: 'OSIRIS-REx returns', agency: 'NASA', flag: '🇺🇸',
    story: 'The capsule that fell into the Utah desert held 120 grams of asteroid Bennu — which had nearly swallowed the spacecraft when its surface behaved like a ball pit during collection. The sample is laced with organics and evidence of an ancient watery parent world.',
    disc: 'Pristine building blocks of the solar system, now in labs worldwide.',
    q: 'OSIRIS-REx sample capsule' },
  { id: 'im1', era: 'newspace', date: '2024-02-22', name: 'Odysseus · IM-1', agency: 'Intuitive Machines', flag: '🇺🇸',
    story: 'The first American lunar landing since 1972 — and the first ever by a private company. It caught a leg and tipped over on touchdown, but kept working: a scrappy preview of the commercial Moon rush now underway.',
    disc: 'The Moon is open for business.',
    fly: { luna: true },
    q: 'Intuitive Machines Odysseus' },
  { id: 'change6', era: 'newspace', date: '2024-06-25', name: 'Chang’e 6', agency: 'CNSA', flag: '🇨🇳',
    story: 'Nobody had ever brought back rock from the Moon’s far side — the half we never see. Chang’e 6 landed in the vast South Pole–Aitken basin, drilled, and flew nearly two kilograms home via lunar-orbit rendezvous.',
    disc: 'Far-side samples: a first for any nation, and clues to why the Moon’s two faces differ.',
    fly: { luna: true },
    q: 'Change 6 far side sample' },
  { id: 'polaris', era: 'newspace', date: '2024-09-12', name: 'Polaris Dawn', agency: 'SpaceX (private)', flag: '🇺🇸',
    story: 'A privately funded crew flew farther from Earth than anyone since Apollo, and Jared Isaacman and Sarah Gillis stepped outside in new slimline suits — the first spacewalk in history conducted by private citizens.',
    disc: 'The spacewalk club is no longer government-only.',
    q: 'Polaris Dawn spacewalk' },
  { id: 'clipper', era: 'newspace', date: '2024-10-14', name: 'Europa Clipper', agency: 'NASA', flag: '🇺🇸',
    story: 'The largest planetary spacecraft NASA has ever built is on its way to the ocean moon Galileo discovered and the Galileo mission unmasked. From 2030 it will dive past Europa dozens of times, tasting its plumes for the chemistry of life.',
    disc: 'The life question, headed for its most promising address. The story continues below — live.',
    fly: { moon: 'Europa' },
    q: 'Europa Clipper spacecraft' },
];
